# Generated by Django 6.1 on 2026-08-31 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroom',
            name='room_type',
            field=models.CharField(choices=[('1v1', '1v1'), ('2v2', '2v2 Team Battle')], default='1v1', max_length=3),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='team1_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='team2_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('local', 'Local Battle'), ('private', 'Private Room'), ('quick', 'Quick Match'), ('friend', 'Friend Challenge'), ('team_2v2', '2v2 Team Battle')], max_length=12),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='slot',
            field=models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2'), ('t1p1', 'Team 1 Player 1'), ('t1p2', 'Team 1 Player 2'), ('t2p1', 'Team 2 Player 1'), ('t2p2', 'Team 2 Player 2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='privateroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for players'), ('filling', 'Filling slots'), ('ready', 'All players ready'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='waiting', max_length=15),
        ),
    ]
