# Generated by Django 6.1 on 2026-09-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_privateroom_room_type_privateroom_team1_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for players'), ('filling', 'Filling slots'), ('ready', 'All players ready'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='waiting', max_length=15),
        ),
    ]
