# Generated by Django 6.1 on 2026-09-26 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0003_alter_privateroom_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroom',
            name='max_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_rooms_p3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_rooms_p4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateroom',
            name='player5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_rooms_p5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='slot',
            field=models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2'), ('player3', 'Player 3'), ('player4', 'Player 4'), ('player5', 'Player 5'), ('t1p1', 'Team 1 Player 1'), ('t1p2', 'Team 1 Player 2'), ('t2p1', 'Team 2 Player 1'), ('t2p2', 'Team 2 Player 2')], max_length=10),
        ),
    ]
