# Generated by Django 6.1 on 2026-09-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0004_privateroom_max_players_privateroom_player3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateroom',
            name='max_players',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
