# Generated by Django 6.1 on 2026-08-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penskin',
            name='asset_key',
            field=models.CharField(default='classic-blue', help_text='Key for vector rendering engine', max_length=40),
        ),
        migrations.AlterField(
            model_name='pen',
            name='kind',
            field=models.CharField(choices=[('classic', 'Classic Ball Pen'), ('heavy', 'Heavy Pen'), ('speed', 'Speed Pen'), ('precision', 'Precision Pen'), ('balanced', 'Balanced Pen')], max_length=20, unique=True),
        ),
    ]
